### ISSUE TITLE
Application fails on launch

### ISSUE THREAD

**Issue by EzzypooOfNazareth** [rohatsu/rtdoom#2]
After building the project using Visual Studio Community 2017, using the ISO C++17 standard, the project is unable to launch. I have tried with multiple different wad files, but on startup all I get is a blank white screen, followed by an immediate crash. Would appreciate any help as I'm very interested in the project.

**Comment by rohatsu** [comment]
Hey, thanks for trying it out, I've tested Freedoom WADs just now and indeed it was crashing, I think they might have gotten updated since I was testing originally (the original Doom 1 WAD file seems to work). I've added a fix for the latest Freedoom WADs and it should now work - in Visual Studio build Release x86 profile, then drop off .wad file into Release directory and start the .exe . If you're still getting a crash then build Debug x86 profile, drop .wad into rtdoom directory (where code is), and start debugger (F5), then post here what error is thrown on crash.

**Comment by EzzypooOfNazareth** [comment]
![image](https://user-images.githubusercontent.com/26283001/110792753-c684a900-8241-11eb-9005-f1b3c4cafa91.png)

After attempting to use the fix branch I now do not crash on startup, however I receive the error message from above, when trying to debug it brings me to this point in the code.

![image](https://user-images.githubusercontent.com/26283001/110792960-0e0b3500-8242-11eb-8b5e-26e41409e0a1.png)


I appreciate the quick response and support.

**Comment by rohatsu** [comment]
Hm, it suggests an issue with processing the .wad file... can you try the attached binary release? I've tried it on two PCs and should start fine, the .wad already included.
[rtdoom.zip](https://github.com/rohatsu/rtdoom/files/6126342/rtdoom.zip)

**Comment by EzzypooOfNazareth** [comment]
Unfortunately even the bin did not work. I still receive a blank white screen followed by a crash. Perhaps it is an issue on my personal system.

**Comment by rohatsu** [comment]
It's most likely this is a legitimate error (for example an inconsistency in the .wad file) and on your system it's causing issues but on some systems it passes. I've added a check around the line you were getting the error, could you try latest code?

**Comment by rohatsu** [comment]
BTW feel free to send me a DM on twitter (@mausmoto) I can help you debug remotely.

**Comment by EzzypooOfNazareth** [comment]
I very much appreciate your willingness to help me out with this, I do not have a twitter, but if you have an insta, discord, or teams account I have those available. 

As for the new repo, this also resulted in a crash, however there was a new error appearing this time
![image](https://user-images.githubusercontent.com/26283001/110873913-bb149a80-82a0-11eb-953c-910df8dea8d7.png)

I also noticed this project uses sdl2 and glm, there was a stackoverflow page that I had open that has to do with an issue I'm having on another bspviewer, I will link the page [opengl wrangling](https://gamedev.stackexchange.com/questions/162904/access-violation-executing-location-0x00000000)

**Comment by rohatsu** [comment]
Got it, but you can't even run the software version, can you? In any case let's move the chat to Discord, my username is Mausimus#7621
